# Week 2 exercises: NumPy, Pandas, and Modules

*Complete all exercises in this notebook during week 2. The exercises are not submitted — this is purely for your own learning and for preparing for the assignments, project and exam.*

Note! You should always complete the tasks first without using AI. If you need AI to get through these tasks, then you will not be able to pass the oral exam. AI can be used to check if your code could be simplified or improved after you solve the task.

---

## Part 1: Modules, Packages and Libraries

### Exercise 1: Importing Modules

a) Import the `math` module and use it to compute the square root of 144 and the value of $e^2$. Print both results.

b) Import only the `ceil` and `floor` functions from the `math` module. Apply both to the value `7.3` and print the results.

c) Import the `random` module with the alias `rng`. Use `rng.randint(1, 100)` to generate and print a random integer between 1 and 100.

In [4]:
# YOUR CODE HERE


import math

print(math.sqrt(144))
print(round(math.e**2, 2))


from math import ceil, floor
print(ceil(7.3))
print(floor(7.3))

import random as rng
print(rng.randint(1, 100))

12.0
7.39
8
7
73

### Exercise 2: Exploring the Standard Library

a) Import the `datetime` module. Create a variable `today` that stores today's date using `datetime.date.today()`. Print the result.

b) Import the `os` module and use `os.getcwd()` to print your current working directory.

In [6]:
# YOUR CODE HERE

import datetime as dt
today = dt.date.today()
print(today)

import os
os.getcwd()

2026-03-25

'C:\\Users\\Win11\\OneDrive - Hanken Svenska handelshogskolan\\Nationalekonomi och Finans\\2586 Python Programming for Business Intelligence\\Cloned Repos\\PythonForBusinessInt2026\\exercises'

## Part 2: NumPy

### Exercise 3: Creating and Inspecting Arrays

a) Import NumPy as `np`. Create a 1D array called `revenues` containing the values: `[120, 95, 200, 180, 160, 210, 190]`. These represent daily revenues in thousands of euros for a week.

b) Print the array's `ndim`, `shape`, `size`, and `dtype`.

c) Create a 2D array with shape `(3, 4)` containing integers from 1 to 12 using `np.arange()` and `.reshape()`. Print the array.

In [9]:
# YOUR CODE HERE

import numpy as np
revenue = np.array([120, 95, 200, 180, 160, 210, 190])

print(revenue.ndim)
print(revenue.shape)
print(revenue.size)
print(revenue.dtype)
print()

a2 = np.array([np.arange(12)])
a2 = a2.reshape(3,4)
print("a2: \n", a2)
print()

a3 = np.array([np.arange(12)]).reshape(3,4)
print("a3: \n", a3)

1
(7,)
7
int32

a2:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

a3:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

### Exercise 4: Array Slicing

Using the `revenues` array:

a) Print the first three elements.

b) Print every other element starting from index 1.

c) Print the array in reversed order.

d) Using the 2D `data` array from Exercise 3c, extract and print:
- The first two rows and first two columns.
- The entire last column.

In [11]:
# YOUR CODE HERE

print(revenue)

print(revenue[:3])
print(revenue[1::2])
print(revenue[::-1])
print()

print(a3)
print()

print(a3[:2, :2])
print()
print(a3[:, -1:])

[120  95 200 180 160 210 190]
[120  95 200]
[ 95 180 210]
[190 210 160 180 200  95 120]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[0 1]
 [4 5]]

[[ 3]
 [ 7]
 [11]]

## Part 3: Pandas — Series and DataFrames

### Exercise 5: Creating a DataFrame

a) Create a DataFrame called `products` from the following dictionary:

```python
product_data = {
    "product": ["Laptop", "Phone", "Tablet", "Monitor"],
    "price": [1200, 800, 450, 350],
    "units_sold": [150, 300, 200, 100]
}
```

b) Print the DataFrame's `index` and `columns`.

c) Add a new column called `revenue` that is the product of `price` and `units_sold`.

d) Print the resulting DataFrame.

In [27]:
import pandas as pd

product_data = {
    "product": ["Laptop", "Phone", "Tablet", "Monitor"],
    "price": [1200, 800, 450, 350],
    "units_sold": [150, 300, 200, 100]
}

products = pd.DataFrame(product_data)

print(products.index)
print(products.columns)

products["revenue"] = products["price"] * products["units_sold"]

print(products)

RangeIndex(start=0, stop=4, step=1)
Index(['product', 'price', 'units_sold'], dtype='object')
   product  price  units_sold  revenue
0   Laptop   1200         150   180000
1    Phone    800         300   240000
2   Tablet    450         200    90000
3  Monitor    350         100    35000

### Exercise 6: Creating DataFrames from Other Sources

a) Create a DataFrame from a list of dictionaries:

```python
employees = [
    {"name": "Anna", "department": "Finance", "salary": 4500},
    {"name": "Erik", "department": "Marketing", "salary": 4000},
    {"name": "Mia", "department": "Finance", "salary": 4800}
]
```

b) Create a DataFrame from a 2D NumPy array of shape `(3, 2)` with random values. Assign column names `"A"` and `"B"` and index labels `"x"`, `"y"`, `"z"`.

c) Print both DataFrames.

In [35]:
# YOUR CODE HERE

employees = pd.DataFrame([
    {"name": "Anna", "department": "Finance", "salary": 4500},
    {"name": "Erik", "department": "Marketing", "salary": 4000},
    {"name": "Mia", "department": "Finance", "salary": 4800}
])

print(employees)


random_df = pd.DataFrame(np.random.rand(3, 2),
                         columns=["A", "B"],
                         index=["a", "b", "c"])

print(random_df)

   name department  salary
0  Anna    Finance    4500
1  Erik  Marketing    4000
2   Mia    Finance    4800
          A         B
a  0.140337  0.512180
b  0.066124  0.521972
c  0.163622  0.232243

## Part 4: Pandas — Subsetting and Slicing

### Exercise 7: Selecting with `.loc`

Use the `products` DataFrame from Exercise 5 for this exercise.

a) Select and print the row at index `1` using `.loc`. What type is the result?

b) Select and print the row at index `1` using `.loc` with double brackets. What type is the result now?

c) Select and print only the `product` and `price` columns for all rows using `.loc`.

d) Select and print the `price` and `units_sold` columns for rows 1 to 2 (inclusive) using `.loc`.

In [59]:
# a. Returns a Series (row as a column of values); selects only the series
products.loc[1]

product        Phone
price            800
units_sold       300
revenue       240000
Name: 1, dtype: object

In [61]:
# b. Returns the whole DataFrame (even if df in question only has one item)
products.loc[[1]]

  product  price  units_sold  revenue
1   Phone    800         300   240000

In [79]:
# c. Comma separates rows from columns; syntax is df.loc[row_selection, column_selection]
print(products.loc[:, ["product", "price"]])

   product  price
0   Laptop   1200
1    Phone    800
2   Tablet    450
3  Monitor    350

In [83]:
# d.
print(products.loc[1:2, ["product", "units_sold"]])

  product  units_sold
1   Phone         300
2  Tablet         200

### Exercise 8: Selecting with `.iloc`

Using the same `products` DataFrame:

a) Select the first two rows using `.iloc`.

b) Select the element in the third row, second column using `.iloc`.

c) Select all rows but only the first and third columns using `.iloc`.

d) What is the difference between `df.loc[0:2]` and `df.iloc[0:2]`? Test both and explain in a comment.

In [127]:
# YOUR CODE HERE

print(products)
print()

print(products.iloc[0:2])
print()

products.iloc[3, 2]
print()

products.iloc[:, [0, 2]]


print("Task d.")
print(products.loc[0:2])
print()

print(products.iloc[0:2])

# .iloc is excluive of the endpoint when slicing columns

# .loc - uses labels, INCLUSIVE on both ends
products.loc[1:3, "product":"price"]   # rows 1,2,3 | columns product, price

# .iloc - uses positions, EXCLUSIVE on the end
products.iloc[1:3, 0:2]               # rows 1,2 | columns product, price

   product  price  units_sold  revenue
0   Laptop   1200         150   180000
1    Phone    800         300   240000
2   Tablet    450         200    90000
3  Monitor    350         100    35000

  product  price  units_sold  revenue
0  Laptop   1200         150   180000
1   Phone    800         300   240000


Task d.
  product  price  units_sold  revenue
0  Laptop   1200         150   180000
1   Phone    800         300   240000
2  Tablet    450         200    90000

  product  price  units_sold  revenue
0  Laptop   1200         150   180000
1   Phone    800         300   240000

  product  price
1   Phone    800
2  Tablet    450

### Exercise 9: Boolean Indexing

Using the `products` DataFrame:

a) Create a boolean mask that identifies products with a price above 500€. Print the mask.

b) Use the mask to subset the DataFrame and print only the expensive products.

c) In a single line, select all products where `units_sold` is greater than or equal to 200. Print the result.

In [159]:
# YOUR CODE HERE
print(products)
print()

above_500 = products["price"] > 500
print(above_500)
print()

print(products[above_500])
print()

print(products[products["units_sold"] >= 200])

   product  price  units_sold  revenue
0   Laptop   1200         150   180000
1    Phone    800         300   240000
2   Tablet    450         200    90000
3  Monitor    350         100    35000

0     True
1     True
2    False
3    False
Name: price, dtype: bool

  product  price  units_sold  revenue
0  Laptop   1200         150   180000
1   Phone    800         300   240000

  product  price  units_sold  revenue
1   Phone    800         300   240000
2  Tablet    450         200    90000

### Exercise 10: Putting It All Together

A small shop tracks weekly sales in a dictionary:

```python
sales_data = {
    "day": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    "customers": [30, 45, 50, 35, 60, 80, 70],
    "sales_eur": [600, 900, 1100, 750, 1300, 1800, 1500]
}
```

a) Create a DataFrame from this dictionary.

b) Add a column `avg_spend` that computes the average spending per customer (i.e., `sales_eur / customers`).

c) Using boolean indexing, filter the DataFrame to show only days where the number of customers exceeded 50.

d) Using `.iloc`, select the data for the weekend (last two rows) and all columns except `day`.

e) What was the total revenue for the week? Use NumPy or Pandas to compute and print the answer.

In [201]:
# YOUR CODE HERE

sales_data = pd.DataFrame ({
    "day": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    "customers": [30, 45, 50, 35, 60, 80, 70],
    "sales_eur": [600, 900, 1100, 750, 1300, 1800, 1500]
})

sales_data["avg_spend"] = round(sales_data["sales_eur"] / sales_data["customers"], 2)

print(sales_data[sales_data["customers"] > 50])
print()

print(sales_data.iloc[-2:, 1:4])
print()


total_revenue = sales_data["sales_eur"].sum()
print(f"Total revenue of the whole week is {total_revenue} euros")

   day  customers  sales_eur  avg_spend
4  Fri         60       1300      21.67
5  Sat         80       1800      22.50
6  Sun         70       1500      21.43

   customers  sales_eur  avg_spend
5         80       1800      22.50
6         70       1500      21.43

Total revenue of the whole week is 7950 euros